### ISSUE TITLE
Flighting the new CustomScript extension for Linux

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-quickstart-templates#2340]
We're rolling out a rewrite of the `Microsoft.OSTCExtensions.CustomScriptForLinux` extension. Pertinent to internal issue, opening an issue to track progress of the rollout in this repository.

# Summary

Notable changes in the new extension
-         Written in Go. Has no dependencies to the waagent or Python.
   - means increased success rate on distros which does not have Python in PATH
-         Strict configuration validation (fails on unrecognized, mistyped extension settings etc)
    - so if the extension config was invalid before (or had extra keys etc) it will fail (I did a manual verification of templates using the extension and opened couple of issues about this)
-         Better retries around file downloads
-         Better error messages for many cases

# Migration

The migration is as simple as changing the:

- publisher to `Microsoft.Azure.Extensions`
- type to `CustomScript`
- version to `2.0`
- and we should add `"autoUpgradeMinorVersion": true` to the extension resources.

# Rollout status

I will be updating & shuffling the list below frequently to determine the slices to rollout and track progress etc. Please subscribe from the right sidebar. (list might not be complete)

### 🍏   Stage 1 (PR: #2344) (2016-08-12)

> **Status:** Complete
> 
> We did not hear any issues from these templates over the past 7 days of flighting
> ![image](https://cloud.githubusercontent.com/assets/159209/17866258/b4e49896-685a-11e6-898c-e7aafdf7bdb2.png)

- [x] [elasticsearch](https://github.com/Azure/azure-quickstart-templates/tree/master/elasticsearch)
- [x] [elasticsearch-centos-3node](https://github.com/Azure/azure-quickstart-templates/tree/master/elasticsearch-centos-3node)
- [x] [elasticsearch-jmeter](https://github.com/Azure/azure-quickstart-templates/tree/master/elasticsearch-jmeter)
- [x] [moodle-cluster-centos](https://github.com/Azure/azure-quickstart-templates/tree/master/moodle-cluster-centos) (template owner reported issues, possibly unrelated)
- [x] [moodle-cluster-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/moodle-cluster-ubuntu)
- [x] [moodle-singlevm-centos](https://github.com/Azure/azure-quickstart-templates/tree/master/moodle-singlevm-centos)
- [x] [moodle-singlevm-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/moodle-singlevm-ubuntu)
- [x] [apache2-on-ubuntu-vm](https://github.com/Azure/azure-quickstart-templates/tree/master/apache2-on-ubuntu-vm)
- [x] [django-app](https://github.com/Azure/azure-quickstart-templates/tree/master/django-app)
- [x] [lamp-app](https://github.com/Azure/azure-quickstart-templates/tree/master/lamp-app)
- [x] [zookeeper-cluster-ubuntu-vm](https://github.com/Azure/azure-quickstart-templates/tree/master/zookeeper-cluster-ubuntu-vm)
- [x] [wordpress-mysql-replication](https://github.com/Azure/azure-quickstart-templates/tree/master/wordpress-mysql-replication)
- [x] [wordpress-single-vm-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/wordpress-single-vm-ubuntu)

-----

### 🍏    Stage 2 (PR: #2389) (2016-08-22)

**Status:** Complete

- [x] [301-dns-forwarder](https://github.com/Azure/azure-quickstart-templates/tree/master/301-dns-forwarder)
- [x] [301-drupal8-vmss-glusterfs-mysql](https://github.com/Azure/azure-quickstart-templates/tree/master/301-drupal8-vmss-glusterfs-mysql)
- [x] [ansible-advancedlinux](https://github.com/Azure/azure-quickstart-templates/tree/master/ansible-advancedlinux)
- [x] [dnx-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/dnx-on-ubuntu)
- [x] [docker-neo4j](https://github.com/Azure/azure-quickstart-templates/tree/master/docker-neo4j)
- [x] [dokku-vm](https://github.com/Azure/azure-quickstart-templates/tree/master/dokku-vm)
- [x] [drone-ubuntu-vm](https://github.com/Azure/azure-quickstart-templates/tree/master/drone-ubuntu-vm)
- [x] [emercoin-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/emercoin-ubuntu)
- [x] [consul-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/consul-on-ubuntu)
- [x] [couchbase-ansible](https://github.com/Azure/azure-quickstart-templates/tree/master/couchbase-ansible)
- [x] [couchbase-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/couchbase-on-ubuntu)
- [x] [hazelcast-vm-cluster](https://github.com/Azure/azure-quickstart-templates/tree/master/hazelcast-vm-cluster)
- [x] [influx-blockchain-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/influx-blockchain-ubuntu)
- [x] [intel-lustre-client-server](https://github.com/Azure/azure-quickstart-templates/tree/master/intel-lustre-client-server)
- [x] [intel-lustre-clients-on-centos](https://github.com/Azure/azure-quickstart-templates/tree/master/intel-lustre-clients-on-centos)
- [x] [intel-lustre-clients-vmss-centos](https://github.com/Azure/azure-quickstart-templates/tree/master/intel-lustre-clients-vmss-centos)
- [x] [iomad-cluster-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/iomad-cluster-ubuntu)
- [x] [iomad-singlevm-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/iomad-singlevm-ubuntu)
- [x] [kafka-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/kafka-on-ubuntu)
- [x] [kafka-ubuntu-multidisks](https://github.com/Azure/azure-quickstart-templates/tree/master/kafka-ubuntu-multidisks)
- [x] [lap-mysql-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/lap-mysql-ubuntu)
- [x] [manifold-endpoint](https://github.com/Azure/azure-quickstart-templates/tree/master/manifold-endpoint)
- [x] [memcached-multi-vm-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/memcached-multi-vm-ubuntu)
- [x] [minecraft-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/minecraft-on-ubuntu)
- [x] [monero-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/monero-on-ubuntu)

-----

### 🍏   Stage 3 (PR: #2435) (2016-09-01)

**Status:** Complete, no issues reported.

- [x] [apprenda60-small](https://github.com/Azure/azure-quickstart-templates/tree/master/apprenda60-small)
- [x] [bitcore-centos-vm](https://github.com/Azure/azure-quickstart-templates/tree/master/bitcore-centos-vm)
- [x] [bitshares-ubuntu-vm](https://github.com/Azure/azure-quickstart-templates/tree/master/bitshares-ubuntu-vm)
- [x] [bitswift-blockchain-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/bitswift-blockchain-ubuntu)
- [x] [blocknet-blockchain-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/blocknet-blockchain-on-ubuntu)
- [x] [bloqenterprise-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/bloqenterprise-on-ubuntu)
- [x] [diagnostics-eventhub-elk](https://github.com/Azure/azure-quickstart-templates/tree/master/diagnostics-eventhub-elk)
- [x] [diagnostics-with-elk](https://github.com/Azure/azure-quickstart-templates/tree/master/diagnostics-with-elk)
- [x] [digibyte-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/digibyte-on-ubuntu)
- [x] [diskraid-ubuntu-vm](https://github.com/Azure/azure-quickstart-templates/tree/master/diskraid-ubuntu-vm)
- [x] [eris-platform](https://github.com/Azure/azure-quickstart-templates/tree/master/eris-platform)
- [x] [ethereum-cpp-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/ethereum-cpp-on-ubuntu)
- [x] [gluster-file-system](https://github.com/Azure/azure-quickstart-templates/tree/master/gluster-file-system)
- [x] [go-ethereum-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/go-ethereum-on-ubuntu)
- [x] [go-expanse-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/go-expanse-on-ubuntu)
- [x] [haproxy-redundant-floatingip-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/haproxy-redundant-floatingip-ubuntu)
- [x] [jenkins-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/jenkins-on-ubuntu)
- [x] [jumbucks-blockchain-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/jumbucks-blockchain-ubuntu)
- [x] [mongodb-high-availability](https://github.com/Azure/azure-quickstart-templates/tree/master/mongodb-high-availability)
- [x] [mongodb-nodejs-high-availability](https://github.com/Azure/azure-quickstart-templates/tree/master/mongodb-nodejs-high-availability)
- [x] [mongodb-on-centos](https://github.com/Azure/azure-quickstart-templates/tree/master/mongodb-on-centos)
- [x] [mongodb-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/mongodb-on-ubuntu)
- [x] [mongodb-replica-set-centos](https://github.com/Azure/azure-quickstart-templates/tree/master/mongodb-replica-set-centos)
- [x] [mongodb-sharding-centos](https://github.com/Azure/azure-quickstart-templates/tree/master/mongodb-sharding-centos)
- [x] [multichain-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/multichain-on-ubuntu)
- [x] [mysql-ha-pxc](https://github.com/Azure/azure-quickstart-templates/tree/master/mysql-ha-pxc)
- [x] [mysql-mha-haproxy-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/mysql-mha-haproxy-ubuntu)
- [x] [mysql-replication](https://github.com/Azure/azure-quickstart-templates/tree/master/mysql-replication)
- [x] [mysql-standalone-server-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/mysql-standalone-server-ubuntu)
- [x] [nagios-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/nagios-on-ubuntu)
- [x] [netki-wns-api-server-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/netki-wns-api-server-on-ubuntu)
- [x] [nylas-email-sync-engine](https://github.com/Azure/azure-quickstart-templates/tree/master/nylas-email-sync-engine)
- [x] [openchain-blockchain-coinprism](https://github.com/Azure/azure-quickstart-templates/tree/master/openchain-blockchain-coinprism)
- [x] [openedx-devstack-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/openedx-devstack-ubuntu)
- [x] [openedx-fullstack-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/openedx-fullstack-ubuntu)
- [x] [openjdk-tomcat-ubuntu-vm](https://github.com/Azure/azure-quickstart-templates/tree/master/openjdk-tomcat-ubuntu-vm)
- [x] [openldap-cluster-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/openldap-cluster-ubuntu)
- [x] [openldap-singlevm-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/openldap-singlevm-ubuntu)
- [x] [puppet-agent-linux](https://github.com/Azure/azure-quickstart-templates/tree/master/puppet-agent-linux)
- [x] [puppet-enterprise-cluster](https://github.com/Azure/azure-quickstart-templates/tree/master/puppet-enterprise-cluster)
- [x] [python-proxy-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/python-proxy-on-ubuntu)
- [x] [radium-blockchain-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/radium-blockchain-ubuntu)
- [x] [redis-high-availability](https://github.com/Azure/azure-quickstart-
templates/tree/master/redis-high-availability)

-----

### 🍏   Stage 4 - (PR: #2450) (2016-09-08)

> **Status**: Completed.

- [x] [201-customscript-extension-azure-storage-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/201-customscript-extension-azure-storage-on-ubuntu)
- [x] [201-customscript-extension-public-storage-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/201-customscript-extension-public-storage-on-ubuntu)
- [x] [201-dependency-between-scripts-using-extensions](https://github.com/Azure/azure-quickstart-templates/tree/master/201-dependency-between-scripts-using-extensions)
- [x] [201-discover-private-ip-dynamically](https://github.com/Azure/azure-quickstart-templates/tree/master/201-discover-private-ip-dynamically)
- [x] [201-traffic-manager-vm](https://github.com/Azure/azure-quickstart-templates/tree/master/201-traffic-manager-vm)
- [x] [201-vm-linux-dynamic-data-disks](https://github.com/Azure/azure-quickstart-templates/tree/master/201-vm-linux-dynamic-data-disks)
- [x] [201-vmss-lapstack-autoscale](https://github.com/Azure/azure-quickstart-templates/tree/master/201-vmss-lapstack-autoscale)
- [x] [301-custom-images-at-scale](https://github.com/Azure/azure-quickstart-templates/tree/master/301-custom-images-at-scale)
- [x] [centos-2nics-lb-cluster](https://github.com/Azure/azure-quickstart-templates/tree/master/centos-2nics-lb-cluster)
- [x] [chef-server-compliance-delivery-devops](https://github.com/Azure/azure-quickstart-templates/tree/master/chef-server-compliance-delivery-devops)
- [x] [cloudera-on-centos](https://github.com/Azure/azure-quickstart-templates/tree/master/cloudera-on-centos)
- [x] [concourse-ci](https://github.com/Azure/azure-quickstart-templates/tree/master/concourse-ci)
- [x] [datastax](https://github.com/Azure/azure-quickstart-templates/tree/master/datastax)
- [x] [openshift-origin-rhel](https://github.com/Azure/azure-quickstart-templates/tree/master/openshift-origin-rhel)
- [x] [opensis-cluster-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/opensis-cluster-ubuntu)
- [x] [opensis-singlevm-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/opensis-singlevm-ubuntu)
- [x] [openvpn-access-server-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/openvpn-access-server-ubuntu)
- [x] [phabricator-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/phabricator-on-ubuntu)
- [x] [postgresql-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/postgresql-on-ubuntu)
- [x] [postgresql-standalone-server-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/postgresql-standalone-server-ubuntu)
- [x] [sap-2-tier-marketplace-image](https://github.com/Azure/azure-quickstart-templates/tree/master/sap-2-tier-marketplace-image)
- [x] [sap-2-tier-user-disk](https://github.com/Azure/azure-quickstart-templates/tree/master/sap-2-tier-user-disk)
- [x] [sap-2-tier-user-image](https://github.com/Azure/azure-quickstart-templates/tree/master/sap-2-tier-user-image)
- [x] [sap-3-tier-marketplace-image](https://github.com/Azure/azure-quickstart-templates/tree/master/sap-3-tier-marketplace-image)
- [x] [sap-3-tier-user-image](https://github.com/Azure/azure-quickstart-templates/tree/master/sap-3-tier-user-image)
- [x] [scrapy-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/scrapy-on-ubuntu)
- [x] [shadow-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/shadow-on-ubuntu)
- [x] [shibboleth-cluster-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/shibboleth-cluster-ubuntu)
- [x] [shibboleth-singlevm-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/shibboleth-singlevm-ubuntu)
- [x] [slurm](https://github.com/Azure/azure-quickstart-te201-mplates/tree/master/slurm)
- [x] [slurm-on-sles12-hpc](https://github.com/Azure/azure-quickstart-templates/tree/master/slurm-on-sles12-hpc)
- [x] [spark-and-cassandra-on-centos](https://github.com/Azure/azure-quickstart-templates/tree/master/spark-and-cassandra-on-centos)
- [x] [spark-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/spark-on-ubuntu)
- [x] [spark-ubuntu-multidisks](https://github.com/Azure/azure-quickstart-templates/tree/master/spark-ubuntu-multidisks)
- [x] [splunk-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/splunk-on-ubuntu)
- [x] [sqldb-django-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/sqldb-django-on-ubuntu)
- [x] [syscoin-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/syscoin-on-ubuntu)
- [x] [torque-cluster](https://github.com/Azure/azure-quickstart-templates/tree/master/torque-cluster)
- [x] [trend-chef-splunk-security](https://github.com/Azure/azure-quickstart-templates/tree/master/trend-chef-splunk-security)
- [x] [ubuntu-desktop-gnome](https://github.com/Azure/azure-quickstart-templates/tree/master/ubuntu-desktop-gnome)
- [x] [ubuntu-desktop-xfce-rdp](https://github.com/Azure/azure-quickstart-templates/tree/master/ubuntu-desktop-xfce-rdp)
- [x] [vcash-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/vcash-on-ubuntu)
- [x] [vertx-openjdk-apache-mysql-on-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/vertx-openjdk-apache-mysql-on-ubuntu)
- [x] [viacoin-blockchain-ubuntu](https://github.com/Azure/azure-quickstart-templates/tree/master/viacoin-blockchain-ubuntu)
- [x] [vsts-fullbuild-ubuntu-vm](https://github.com/Azure/azure-quickstart-templates/tree/master/vsts-fullbuild-ubuntu-vm)
- [x] [vsts-minbuildjava-ubuntu-vm](https://github.com/Azure/azure-quickstart-templates/tree/master/vsts-minbuildjava-ubuntu-vm)
- [x] [website-cluster-centos](https://github.com/Azure/azure-quickstart-templates/tree/master/website-cluster-centos)
- [x] [xtremedata-dbx-cluster-centos](https://github.com/Azure/azure-quickstart-templates/tree/master/xtremedata-dbx-cluster-centos)

-----

### 🍏   Stage 5 (PR: #2502) (2016-09-19)

> **Status**:  Completed

- [x] [.github/CONTRIBUTING.md](https://github.com/Azure/azure-quickstart-templates/tree/master/.github/CONTRIBUTING.md)
- [x] [1-CONTRIBUTION-GUIDE/best-practices.md](https://github.com/Azure/azure-quickstart-templates/tree/master/1-CONTRIBUTION-GUIDE/best-practices.md)
- [x] [201-dependency-between-scripts-using-extensions/install-mongo.json](https://github.com/Azure/azure-quickstart-templates/tree/master/201-dependency-between-scripts-using-extensions/install-mongo.json)
- [x] [201-vmss-bottle-autoscale/azuredeploy.json](https://github.com/Azure/azure-quickstart-templates/tree/master/201-vmss-bottle-autoscale/azuredeploy.json)
- [x] [ansible-advancedlinux/azuredeploy.json](https://github.com/Azure/azure-quickstart-templates/tree/master/ansible-advancedlinux/azuredeploy.json)
- [x] [influx-blockchain-ubuntu/azuredeploy.json](https://github.com/Azure/azure-quickstart-templates/tree/master/influx-blockchain-ubuntu/azuredeploy.json)
- [x] [intel-lustre-client-server/azuredeploy.json](https://github.com/Azure/azure-quickstart-templates/tree/master/intel-lustre-client-server/azuredeploy.json)
- [x] [intel-lustre-client-server/monitoring.json](https://github.com/Azure/azure-quickstart-templates/tree/master/intel-lustre-client-server/monitoring.json)
- [x] [kafka-ubuntu-multidisks/README.md](https://github.com/Azure/azure-quickstart-templates/tree/master/kafka-ubuntu-multidisks/README.md)
- [x] [kafka-ubuntu-multidisks/zookeeper-resources.json](https://github.com/Azure/azure-quickstart-templates/tree/master/kafka-ubuntu-multidisks/zookeeper-resources.json)
- [x] [lap-neo4j-ubuntu/nested/lanplap-resources.json](https://github.com/Azure/azure-quickstart-templates/tree/master/lap-neo4j-ubuntu/nested/lanplap-resources.json)
- [x] [lap-neo4j-ubuntu/nested/lanpneo4j-resources.json](https://github.com/Azure/azure-quickstart-templates/tree/master/lap-neo4j-ubuntu/nested/lanpneo4j-resources.json)
- [x] [memcached-multi-vm-ubuntu/README.md](https://github.com/Azure/azure-quickstart-templates/tree/master/memcached-multi-vm-ubuntu/README.md)
- [x] [mongodb-nodejs-high-availability/frontend-resource.json](https://github.com/Azure/azure-quickstart-templates/tree/master/mongodb-nodejs-high-availability/frontend-resource.json)
- [x] [nxt-blockchain-ubuntu/azuredeploy.json](https://github.com/Azure/azure-quickstart-templates/tree/master/nxt-blockchain-ubuntu/azuredeploy.json)
- [x] [openedx-scalable-ubuntu/azuredeploy.json](https://github.com/Azure/azure-quickstart-templates/tree/master/openedx-scalable-ubuntu/azuredeploy.json)
- [x] [postgresql-on-ubuntu/README.md](https://github.com/Azure/azure-quickstart-templates/tree/master/postgresql-on-ubuntu/README.md)
- [x] [stampery-trailbot-ubuntu/azuredeploy.json](https://github.com/Azure/azure-quickstart-templates/tree/master/stampery-trailbot-ubuntu/azuredeploy.json)
- [x] [ubuntu-apache-test-page/azuredeploy.json](https://github.com/Azure/azure-quickstart-templates/tree/master/ubuntu-apache-test-page/azuredeploy.json)
- [x] [vsts-tomcat-redhat-vm/azuredeploy.json](https://github.com/Azure/azure-quickstart-templates/tree/master/vsts-tomcat-redhat-vm/azuredeploy.json)
- [x] [zabbix-monitoring-cluster/nested/monitoringAgentByVms.json](https://github.com/Azure/azure-quickstart-templates/tree/master/zabbix-monitoring-cluster/nested/monitoringAgentByVms.json)
- [x] [zabbix-monitoring-cluster/nested/monitoringServer.json](https://github.com/Azure/azure-quickstart-templates/tree/master/zabbix-monitoring-cluster/nested/monitoringServer.json)
- [x] [vsts-tomcat-ubuntu-vm/azuredeploy.json](https://github.com/Azure/azure-quickstart-templates/tree/master/vsts-tomcat-ubuntu-vm/azuredeploy.json)

-----

### 🍏  Stage 6 (PR: #2652)

> **Status**:  Completed

The following templates will be migrated once `CustomScript` extension is available in `AzureChina` by @[bingosummer] 

- [x] [bosh-setup](https://github.com/Azure/azure-quickstart-templates/tree/master/bosh-setup)
- [x] [bosh-cf-crossregion](https://github.com/Azure/azure-quickstart-templates/tree/master/bosh-cf-crossregion)

**Comment by singhkays** [comment]
FYI: @bmoore-msft @gatneil @bmoore-msft @simongdavies @marcvaneijk

**Comment by ahmetalpbalkan** [comment]
This is now completed.

cc: @gatneil @danielsollondon
